# Generated by Django 3.0.8 on 2020-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publishedAt', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.URLField()),
            ],
        ),
    ]
